@host = http://localhost:3000/api/users
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTcwMzIyNzQwNiwiZXhwIjoxNzAzMjcwNjA2fQ.yQZZflmTi_vKdL4bfl_HKpMAZuvU_YZXHdjukNbI1cg

### 내 정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}
